#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "phanpy"
name = "Phanpy"

description.en = "Minimalistic opinionated Fediverse ⁂ web client"
description.fr = "Client Fediverse ⁂ minimaliste et original"
description.es = "Cliente para el Fediverso ⁂ minimalista y original"

version = "20250312~ynh1"

maintainers = ["ghose"]

[upstream]
license = "MIT"
website = "https://phanpy.social/"
demo = "https://phanpy.social/"
code = "https://github.com/cheeaun/phanpy"

[integration]
yunohost = '>= 12.0.9'
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "15M"
ram.build = "70M"
ram.runtime = "10M"

[antifeatures]
arbitrary-limitations.en = "(Optional) In-line translations feature depends on 3rd party services: Lingva API, a frontend for Google Translate hosted on phanpy.social."

[install]

    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/phanpy"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/YunoHost-Apps/phanpy_ynh/raw/refs/heads/testing/ynh-release/phanpy.tar.gz"
        sha256 = "7f2b1642f7497eace798c25296d819c75911c27e8532af0d7a2c3b79b3aadb9c"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = ".*\\.tar\\.gz"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
