#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "phanpy"
name = "Phanpy"

description.en = "A minimalistic opinionated Fediverse ⁂ web client"
description.fr = "Un client web Fediverse ⁂ minimaliste avec opinion"

version = "0.2~ynh1"

maintainers = ["ghose"]

[upstream]
license = "MIT License"
website = "https://phanpy.social/"
demo = "https://phanpy.social/"

code = "https://github.com/cheeaun/phanpy"

[integration]
yunohost = '>= 11.2.30'
helpers_version = "2.1"
architectures = "all" 
multi_instance = true
ldap = "false" 
sso = "not_relevant"
disk = "5M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/phanpy"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/cheeaun/phanpy/releases/download/2024.10.15.e3df9ff/phanpy-dist.tar.gz"
        sha256 = "2153f1ea7214f2c200e4aa081eb1351082ff59b7d9a92a73252d5fcbdceee68c"

        autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
